FROM gradle:8.4.0-jdk17 AS build
WORKDIR /home/gradle
COPY --chown=gradle:gradle . .
USER gradle
RUN gradle clean build --no-daemon

FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
RUN adduser -D eventus
COPY --from=build /home/gradle/build/libs/*.jar /app/app.jar
USER eventus
EXPOSE 8080
CMD ["java", "-jar", "/app/app.jar"]
